# Source: lighthouse/templates/foghorn-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-foghorn
  labels:
    chart: "lighthouse-1.16.3"
    app: lighthouse-foghorn
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
    wave.pusher.com/update-on-config-change: 'true'
  namespace: jx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse-foghorn
  template:
    metadata:
      labels:
        app: lighthouse-foghorn
      annotations:
        jenkins-x.io/hash: '8b0342a4fe27e2cd23df2411dbfad365640854d7a651414fe23326f426a15450'
    spec:
      serviceAccountName: lighthouse-foghorn
      containers:
      - name: lighthouse-foghorn
        image: ghcr.io/jenkins-x/lighthouse-foghorn:1.16.3
        imagePullPolicy: IfNotPresent
        args:
        - "--namespace=jx"
        env:
        - name: "GIT_KIND"
          value: "github"
        - name: "GIT_SERVER"
          value: "https://github.com"
        - name: "GIT_USER"
          value: srikanthbhandary
        - name: "GIT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: lighthouse-oauth-token
              key: oauth
        - name: "HMAC_TOKEN"
          valueFrom:
            secretKeyRef:
              name: lighthouse-hmac-token
              key: hmac
        - name: "JX_LOG_FORMAT"
          value: "json"
        - name: "LOGRUS_FORMAT"
          value: "json"
        - name: LOGRUS_SERVICE
          value: "lighthouse"
        - name: LOG_LEVEL
          value: "info"
        - name: LOGRUS_SERVICE_VERSION
          value: "1.16.3"
        - name: LOGRUS_STACK_SKIP
          value: ""
        - name: DEFAULT_PIPELINE_RUN_SERVICE_ACCOUNT
          value: "tekton-bot"
        - name: DEFAULT_PIPELINE_RUN_TIMEOUT
          value: "2h0m0s"
        - name: FILE_BROWSER
          value: "git"
        - name: JX_DEFAULT_IMAGE
          value: "ghcr.io/jenkins-x/builder-maven:2.1.149-768"
        - name: LIGHTHOUSE_DASHBOARD_TEMPLATE
          value: "namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}"
        - name: LIGHTHOUSE_VERSIONSTREAM_JENKINS_X_JX3_PIPELINE_CATALOG
          value: "f491772ffe37aa018f192860c76705b3bf342876"
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi
        volumeMounts:
      volumes:
      terminationGracePeriodSeconds: 180
